Repository baresip/baresip, pull requests merged in 2021-04, with the labels that each got.

#1350 GTK caller history
  modules/gtk/gtk_mod.c
  modules/gtk/gtk_mod.h
Labels: GUI

#1385 dtls_srtp: use elliptic curve cryptography
  docs/examples/config
  modules/dtls_srtp/dtls_srtp.c
  src/config.c
Labels: Security

#1376 Tls sipcert per acc
  docs/examples/accounts
  src/account.c
  src/core.h
  src/ua.c
Labels: Security

#1349 ua,uag: split ua.c and uag.c
  src/core.h
  src/srcs.mk
  src/ua.c
  src/uag.c
Labels: Refactoring
